# Generated by Django 4.0.2 on 2022-03-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='color',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
