# Generated by Django 4.0.2 on 2022-03-26 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_users_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='color',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
